// GENERATED by tools/data/build-masters-seed.cjs — do not edit by hand.
//
// Source: data\itemcatagory.json (10 of 27 categories)
//         data\itemmaster.json (10 of 16 items)
//
// The exports are paginated and only page 1 of each is present, so this covers
// 10/27 categories and 10/16 items. Drop the remaining pages into
// data/ and re-run the generator; `masters-seed-data.test.ts` asserts the counts match, so the
// suite fails until the seed and the export agree.
//
// `level` and `path` are recomputed from `parentCategory` rather than copied: every record in
// the export carries `level: 0` and a bare path, including the ones with a parent.

import type {
  ItemAlternateUom,
  ItemCategorySettings,
  ItemGstRates,
  ItemLobConfig,
  ItemNature,
  ItemReorderSettings,
  ItemType,
  TaxCategory,
  TrackingType,
} from '@/types/firestore'

export interface SeedCategory {
  code: string
  name: string
  type: 'Raw Material' | 'Service'
  parentCode: string | null
  description: string | null
  icon: string | null
  color: string | null
  displayOrder: number
  applicableAttributes: string[]
  settings: ItemCategorySettings
  level: number
  path: string
}

export interface SeedItem {
  itemCode: string
  name: string
  description: string | null
  type: ItemType
  nature: ItemNature
  categoryCode: string | null
  subCategoryCode: string | null
  primaryUom: SeedUomRef | null
  purchaseUom: SeedUomRef | null
  salesUom: SeedUomRef | null
  alternateUoms: ItemAlternateUom[]
  taxCategory: TaxCategory
  gstPercent: number
  gstRates: ItemGstRates
  sellingPrice: number
  purchasePrice: number
  mrp: number
  stockTracked: boolean
  trackingType: TrackingType
  shelfLifeDays: number | null
  reorder: ItemReorderSettings
  hasVariants: boolean
  variantAttributes: string[]
  images: string[]
  lob: ItemLobConfig
  isSystem: boolean
}

/** The export embeds the code, name and symbol but not an id this app can use - its Mongo _id
 *  belongs to the reference system. The seeder fills the id in from the UOM it writes. */
export interface SeedUomRef {
  code: string
  name: string
  symbol: string
}

/** Totals declared by the export's own pagination, asserted in the test. */
export const REFERENCE_TOTALS = {
  categories: 27,
  items: 16,
} as const

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    code: 'SPARE_PARTS',
    name: 'Spare Parts',
    type: 'Raw Material',
    parentCode: null,
    description: 'Mobile repair साठी लागणारे सर्व spare parts',
    icon: 'screwdriver-wrench',
    color: '#e74c3c',
    displayOrder: 1,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 0,
    path: 'SPARE_PARTS',
  },
  {
    code: 'SPARE_SCREENS',
    name: 'Screens & Displays',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'LCD, AMOLED, OLED displays आणि touch panels',
    icon: 'mobile-screen',
    color: '#c0392b',
    displayOrder: 1,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_SCREENS',
  },
  {
    code: 'SPARE_BATTERIES',
    name: 'Batteries',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Mobile batteries — original आणि compatible',
    icon: 'battery-full',
    color: '#e67e22',
    displayOrder: 2,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_BATTERIES',
  },
  {
    code: 'SPARE_CHARGING',
    name: 'Charging Ports & Flex',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Charging connectors, USB ports, flex cables',
    icon: 'plug',
    color: '#f39c12',
    displayOrder: 3,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_CHARGING',
  },
  {
    code: 'SPARE_CAMERAS',
    name: 'Camera Modules',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Front आणि back camera modules',
    icon: 'camera',
    color: '#8e44ad',
    displayOrder: 4,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_CAMERAS',
  },
  {
    code: 'SPARE_SPEAKERS',
    name: 'Speakers & Mic',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Earpiece speakers, loud speakers, microphones',
    icon: 'volume-high',
    color: '#2980b9',
    displayOrder: 5,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_SPEAKERS',
  },
  {
    code: 'SPARE_BUTTONS',
    name: 'Buttons & Keys',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Power button, volume keys, home button flex',
    icon: 'circle-dot',
    color: '#16a085',
    displayOrder: 6,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_BUTTONS',
  },
  {
    code: 'SPARE_BACK_PANEL',
    name: 'Back Panel & Housing',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Back cover, middle frame, housing parts',
    icon: 'mobile',
    color: '#27ae60',
    displayOrder: 7,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_BACK_PANEL',
  },
  {
    code: 'SPARE_IC_CHIPS',
    name: 'IC & Chips',
    type: 'Raw Material',
    parentCode: 'SPARE_PARTS',
    description: 'Charging IC, network IC, display IC chips',
    icon: 'microchip',
    color: '#2c3e50',
    displayOrder: 8,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 1,
    path: 'SPARE_PARTS/SPARE_IC_CHIPS',
  },
  {
    code: 'ACCESSORIES',
    name: 'Accessories',
    type: 'Raw Material',
    parentCode: null,
    description: 'विक्रीसाठी mobile accessories',
    icon: 'bag-shopping',
    color: '#3498db',
    displayOrder: 2,
    applicableAttributes: [],
    settings: {
      enableBatchTracking: false,
      enableExpiryTracking: false,
      enableSerialTracking: false,
      defaultShelfLifeDays: null,
    },
    level: 0,
    path: 'ACCESSORIES',
  },
]

export const SEED_ITEMS: SeedItem[] = [
  {
    itemCode: 'SRV009',
    name: 'Back Panel / Housing Replacement',
    description: 'Back cover and housing replacement',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV003',
    name: 'Battery Replacement',
    description: 'Battery replacement labour',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV008',
    name: 'Button / Key Repair',
    description: 'Power, volume and home button repair',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV005',
    name: 'Camera Repair / Replacement',
    description: 'Front or rear camera module work',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV004',
    name: 'Charging Port Repair',
    description: 'Charging connector / port repair or replacement',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV014',
    name: 'Data Backup / Transfer',
    description: 'Customer data backup and transfer',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV001',
    name: 'Diagnosis / Inspection',
    description: 'Device checking and fault diagnosis',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV016',
    name: 'General Service Charges',
    description: 'Any other labour or service charge',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV007',
    name: 'Microphone Repair',
    description: 'Mic repair or replacement',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
  {
    itemCode: 'SRV011',
    name: 'Motherboard / Chip Level Repair',
    description: 'Chip-level motherboard repair',
    type: 'service',
    nature: 'Service',
    categoryCode: 'SERVICES',
    subCategoryCode: null,
    primaryUom: {
      code: 'NOS',
      name: 'Numbers',
      symbol: 'nos',
    },
    purchaseUom: null,
    salesUom: null,
    alternateUoms: [],
    taxCategory: 'GST_18',
    gstPercent: 18,
    gstRates: {
      cgst: 0,
      sgst: 0,
      igst: 0,
      cess: 0,
    },
    sellingPrice: 0,
    purchasePrice: 0,
    mrp: 0,
    stockTracked: false,
    trackingType: 'NONE',
    shelfLifeDays: null,
    reorder: {
      minStock: 0,
      reorderPoint: 0,
      reorderQty: 0,
      maxStock: 0,
    },
    hasVariants: false,
    variantAttributes: [],
    images: [],
    lob: {
      sales: {
        isActive: true,
        allowDiscount: true,
        maxDiscountPercent: 100,
      },
      purchase: {
        isActive: false,
        leadTimeDays: 0,
      },
      production: {
        isActive: false,
        isBomItem: false,
      },
      servicePos: {
        isActive: true,
      },
      ecommerce: {
        isActive: false,
      },
    },
    isSystem: true,
  },
]
