/** Attributes rebuilt as custom-field definitions, matching the client's own screen. */
module.exports = {
  pages: {
    masters: {
      attributes: {
        dynamicProductItemAttributes: {
          en: 'Dynamic product/item attributes — color, RAM, storage, etc.',
          hi: 'डायनामिक प्रोडक्ट/आइटम विशेषताएँ — रंग, RAM, स्टोरेज आदि।',
          gu: 'ડાયનેમિક પ્રોડક્ટ/આઇટમ લક્ષણો — રંગ, RAM, સ્ટોરેજ વગેરે.',
        },
        allEntities: { en: 'All entities', hi: 'सभी एंटिटी', gu: 'બધી એન્ટિટી' },
        appliesTo: { en: 'Applies To', hi: 'किस पर लागू', gu: 'કોના પર લાગુ' },
        dataType: { en: 'Data Type', hi: 'डेटा प्रकार', gu: 'ડેટા પ્રકાર' },
        mandatory: { en: 'Mandatory', hi: 'अनिवार्य', gu: 'ફરજિયાત' },
        requireThisFieldWhenCreating: {
          en: 'Require this field when creating items',
          hi: 'आइटम बनाते समय यह फ़ील्ड अनिवार्य करें',
          gu: 'આઇટમ બનાવતી વખતે આ ફીલ્ડ ફરજિયાત કરો',
        },
        autoGenerated: { en: 'AUTO-GENERATED', hi: 'स्वतः बनेगा', gu: 'આપમેળે બનશે' },
        eGColorRam: { en: 'e.g. Color, RAM', hi: 'जैसे रंग, RAM', gu: 'જેમ કે રંગ, RAM' },
        thatCodeIsTaken: {
          en: '"{{name}}" already uses that code. Codes have to be unique.',
          hi: '"{{name}}" पहले से यह कोड उपयोग करता है। कोड अद्वितीय होने चाहिए।',
          gu: '"{{name}}" પહેલેથી આ કોડ વાપરે છે. કોડ અનન્ય હોવા જોઈએ.',
        },
        entity: {
          item: { en: 'Item / Product', hi: 'आइटम / प्रोडक्ट', gu: 'આઇટમ / પ્રોડક્ટ' },
          party: { en: 'Party', hi: 'पार्टी', gu: 'પાર્ટી' },
          jobCard: { en: 'Job Card', hi: 'जॉब कार्ड', gu: 'જોબ કાર્ડ' },
        },
        type: {
          text: { en: 'Text', hi: 'टेक्स्ट', gu: 'ટેક્સ્ટ' },
          number: { en: 'Number', hi: 'संख्या', gu: 'સંખ્યા' },
          date: { en: 'Date', hi: 'तारीख', gu: 'તારીખ' },
          boolean: { en: 'Yes / No', hi: 'हाँ / नहीं', gu: 'હા / ના' },
          select: { en: 'Dropdown', hi: 'ड्रॉपडाउन', gu: 'ડ્રોપડાઉન' },
        },
      },
    },
  },
}
