/** Batch 9 — multi-line JSX text: the app's full sentences, helper text and callouts. */
module.exports = {
  'components.auth.accountDisabledScreen.contactYourOwnerOrAdministratorIf': {
    hi: 'अगर आपको लगता है कि यह गलती है, तो अपने मालिक या प्रशासक से संपर्क करें।',
    gu: 'જો તમને લાગે કે આ ભૂલ છે, તો તમારા માલિક કે વ્યવસ્થાપકનો સંપર્ક કરો.',
  },
  'components.auth.ipBlockedScreen.askAnOwnerToAddYour': {
    hi: 'किसी मालिक से प्रशासन → IP व्हाइटलिस्ट में अपना IP जोड़ने को कहें, या किसी पहले से मंज़ूर नेटवर्क से जुड़ें।',
    gu: 'કોઈ માલિકને વ્યવસ્થાપન → IP વ્હાઇટલિસ્ટમાં તમારું IP ઉમેરવા કહો, અથવા પહેલેથી મંજૂર નેટવર્કથી જોડાઓ.',
  },
  'components.layout.profileDrawer.profileInfo': {
    hi: 'प्रोफ़ाइल जानकारी',
    gu: 'પ્રોફાઇલ માહિતી',
  },
  'components.layout.profileDrawer.changePassword': {
    hi: 'पासवर्ड बदलें',
    gu: 'પાસવર્ડ બદલો',
  },
  'components.layout.profileDrawer.usedForDisplayAndContactChanging': {
    hi: 'दिखाने और संपर्क के लिए। इसे बदलने से वह ईमेल नहीं बदलता जिससे आप लॉग इन करते हैं।',
    gu: 'બતાવવા અને સંપર્ક માટે. આ બદલવાથી તમે જે ઈમેલથી લોગ ઇન કરો છો તે બદલાતું નથી.',
  },
  'components.layout.profileDrawer.profileUpdated': {
    hi: 'प्रोफ़ाइल अपडेट हो गई।',
    gu: 'પ્રોફાઇલ અપડેટ થઈ.',
  },
  'components.layout.profileDrawer.passwordUpdatedYourOtherDevicesStay': {
    hi: 'पासवर्ड बदल गया। आपकी बाकी डिवाइस लॉग इन ही रहेंगी।',
    gu: 'પાસવર્ડ બદલાયો. તમારાં બીજાં ડિવાઇસ લોગ ઇન જ રહેશે.',
  },
  'components.marketing.jobCardMockup.sampleData': {
    hi: 'नमूना जानकारी',
    gu: 'નમૂના માહિતી',
  },
  'components.marketing.jobCardMockup.samsungGalaxyA15BatteryReplacement': {
    hi: 'Samsung Galaxy A15 · बैटरी बदलना',
    gu: 'Samsung Galaxy A15 · બેટરી બદલવી',
  },
  'components.marketing.jobCardMockup.paid1450': {
    hi: '₹1,450 भुगतान',
    gu: '₹1,450 ચૂકવ્યા',
  },
  'components.marketing.marketingNav.signUpFree': {
    hi: 'मुफ़्त साइन अप करें',
    gu: 'મફત સાઇન અપ કરો',
  },
  'components.shared.errorBoundary.anUnexpectedErrorOccurredReloadingThe': {
    hi: 'कोई अनपेक्षित गड़बड़ हो गई। पेज दोबारा लोड करने से यह आमतौर पर ठीक हो जाता है — अगर बार-बार हो, तो हमें बताएं।',
    gu: 'કોઈ અણધારી ખામી થઈ. પાનું ફરી લોડ કરવાથી આ સામાન્યપણે ઠીક થઈ જાય છે — વારંવાર થાય તો અમને જણાવો.',
  },
  'components.shared.patternLock.savePattern': {
    hi: 'पैटर्न सहेजें',
    gu: 'પેટર્ન સાચવો',
  },
  'components.shared.scanJobCardModal.justPointItAutoFocusesZooms': {
    hi: 'बस सामने रखें — यह अपने आप फ़ोकस, ज़ूम करके तुरंत पकड़ लेता है',
    gu: 'ફક્ત સામે રાખો — તે આપોઆપ ફોકસ, ઝૂમ કરીને તરત પકડી લે છે',
  },
  'pages.administration.activeSessions.thisDevice': {
    hi: 'यह डिवाइस',
    gu: 'આ ડિવાઇસ',
  },
  'pages.administration.activeSessions.technicalDetails': {
    hi: 'तकनीकी विवरण',
    gu: 'ટેકનિકલ વિગતો',
  },
  'shared.uniqueIdentifierAutoGeneratedFromName': {
    hi: 'अनोखी पहचान (नाम से अपने आप बनी)',
    gu: 'અનન્ય ઓળખ (નામથી આપોઆપ બનેલી)',
  },
  'pages.administration.createRole.afterCreatingThisRoleYouLl': {
    hi: 'यह भूमिका बनाने के बाद आपको यह करना होगा:',
    gu: 'આ ભૂમિકા બનાવ્યા પછી તમારે આ કરવું પડશે:',
  },
  'pages.administration.createRole.byDefaultNewRolesHaveNo': {
    hi: 'डिफ़ॉल्ट रूप से नई भूमिकाओं को कोई अनुमति और कोई मेन्यू पहुँच नहीं होती।',
    gu: 'ડિફોલ્ટ રીતે નવી ભૂમિકાઓને કોઈ પરવાનગી અને કોઈ મેન્યુ પહોંચ હોતી નથી.',
  },
  'pages.administration.createUser.createANewUserAccountWith': {
    hi: 'भूमिका और अनुमतियों के साथ नया उपयोगकर्ता खाता बनाएं',
    gu: 'ભૂમિકા અને પરવાનગીઓ સાથે નવું વપરાશકર્તા ખાતું બનાવો',
  },
  'pages.administration.ipWhitelist.addIpToWhitelist': {
    hi: 'व्हाइटलिस्ट में IP जोड़ें',
    gu: 'વ્હાઇટલિસ્ટમાં IP ઉમેરો',
  },
  'pages.administration.dashboardLandingTab.whereThisRoleLandsImmediatelyAfter': {
    hi: 'लॉग इन करते ही यह भूमिका कहाँ पहुँचती है।',
    gu: 'લોગ ઇન કરતાં જ આ ભૂમિકા ક્યાં પહોંચે છે.',
  },
  'pages.administration.menusPermissionsTab.grantedViaFullAccess': {
    hi: 'पूरी पहुँच (*) से मिली',
    gu: 'પૂરી પહોંચ (*) થી મળી',
  },
  'pages.administration.roleConfigure.thisIsTheOwnerRoleRemoving': {
    hi: 'यह मालिक भूमिका है। यहाँ से पूरी पहुँच हटाने पर हर मालिक प्रशासन सुविधाओं से बाहर हो सकता है — पक्का हो तभी बदलें।',
    gu: 'આ માલિક ભૂમિકા છે. અહીંથી પૂરી પહોંચ કાઢવાથી દરેક માલિક વ્યવસ્થાપન સુવિધાઓથી બહાર થઈ શકે — ખાતરી હોય તો જ બદલો.',
  },
  'pages.administration.roleManagement.showActiveRoles': {
    hi: 'सक्रिय भूमिकाएं दिखाएं',
    gu: 'સક્રિય ભૂમિકાઓ બતાવો',
  },
  'pages.administration.roleManagement.reloadFromServer': {
    hi: 'सर्वर से दोबारा लोड करें',
    gu: 'સર્વરથી ફરી લોડ કરો',
  },
  'pages.administration.roleManagement.thisRoleHasFullAccessBy': {
    hi: 'इस भूमिका को परिभाषा से ही पूरी पहुँच है और इसे सिर्फ़ कोई दूसरा मालिक संभाल सकता है, इसलिए इसे बंद या हटाया नहीं जा सकता।',
    gu: 'આ ભૂમિકાને વ્યાખ્યાથી જ પૂરી પહોંચ છે અને તેને ફક્ત બીજો માલિક સંભાળી શકે, તેથી તેને બંધ કે કાઢી શકાતી નથી.',
  },
  'pages.administration.userManagement.addNewUser': {
    hi: 'नया उपयोगकर्ता जोड़ें',
    gu: 'નવો વપરાશકર્તા ઉમેરો',
  },
  'pages.dashboard.dashboard.hereSWhatSHappeningIn': {
    hi: 'आपके सर्विस सेंटर में क्या चल रहा है, यह देखिए।',
    gu: 'તમારા સર્વિસ સેન્ટરમાં શું ચાલી રહ્યું છે, તે જુઓ.',
  },
  'pages.finance.expenses.setThisToHaveTheExpense': {
    hi: 'यह भरने पर खर्च उस पार्टी के खाते में दिखेगा। चाय या भाड़े जैसी चीज़ों के लिए खाली छोड़ें।',
    gu: 'આ ભરવાથી ખર્ચ તે પાર્ટીના ખાતામાં દેખાશે. ચા કે ભાડા જેવી વસ્તુઓ માટે ખાલી છોડો.',
  },
  'pages.finance.partyLedger.closingBalance': { hi: 'अंतिम शेष', gu: 'આખરી બાકી' },
  'pages.finance.payables.alreadyRefunded': {
    hi: 'पहले वापस किया',
    gu: 'પહેલાં પરત કરેલ',
  },
  'pages.finance.supplierPayables.leftEmptyTheBillAgesFrom': {
    hi: 'खाली छोड़ने पर बिल की उम्र उसकी बिल तारीख से गिनी जाती है।',
    gu: 'ખાલી છોડવાથી બિલની ઉંમર તેની બિલ તારીખથી ગણાય છે.',
  },
  'pages.finance.supplierPayables.recordedAsAPaymentOutSo': {
    hi: 'रकम बाहर जाने के रूप में दर्ज, इसलिए यह रोकड़ बही और इस सप्लायर के खाते में दिखता है।',
    gu: 'રકમ બહાર જવા તરીકે નોંધાય, તેથી તે રોકડ ખાતાવહી અને આ સપ્લાયરના ખાતામાં દેખાય છે.',
  },
  'pages.finance.supplierPayables.clearAgeFilter': {
    hi: 'उम्र फ़िल्टर हटाएं',
    gu: 'ઉંમર ફિલ્ટર કાઢો',
  },
  'pages.finance.supplierPayables.recordPayment': {
    hi: 'भुगतान दर्ज करें',
    gu: 'ચુકવણી નોંધો',
  },
  'shared.addCategory': { hi: 'श्रेणी जोड़ें', gu: 'શ્રેણી ઉમેરો' },
  'pages.masters.partyCategories.thisNameWillBeVisibleIn': {
    hi: 'यह नाम पार्टियों और रिपोर्ट में दिखेगा।',
    gu: 'આ નામ પાર્ટીઓ અને રિપોર્ટમાં દેખાશે.',
  },
  'pages.masters.partyCategories.uniqueSystemIdentifierAutoGeneratedBut': {
    hi: 'अनोखी सिस्टम पहचान। अपने आप बनती है, पर बदली जा सकती है।',
    gu: 'અનન્ય સિસ્ટમ ઓળખ. આપોઆપ બને છે, પણ બદલી શકાય છે.',
  },
  'pages.masters.partyCategories.defaultForCustomer': {
    hi: 'ग्राहक के लिए डिफ़ॉल्ट',
    gu: 'ગ્રાહક માટે ડિફોલ્ટ',
  },
  'pages.masters.partyCategories.defaultForSupplier': {
    hi: 'सप्लायर के लिए डिफ़ॉल्ट',
    gu: 'સપ્લાયર માટે ડિફોલ્ટ',
  },
  'pages.masters.paymentModes.addPaymentMode': {
    hi: 'भुगतान तरीका जोड़ें',
    gu: 'ચુકવણી રીત ઉમેરો',
  },
  'pages.masters.uom.setThisOnlyIfThisUom': {
    hi: 'यह तभी भरें जब यह UOM किसी दूसरी में बदलती हो। जैसे 1 इंच = 0.0254 मीटर',
    gu: 'આ ત્યારે જ ભરો જ્યારે આ UOM બીજામાં બદલાય. જેમ કે 1 ઇંચ = 0.0254 મીટર',
  },
  'shared.exportExcel': { hi: 'Excel एक्सपोर्ट', gu: 'Excel એક્સપોર્ટ' },
  'pages.reports.periodSummary.shopExpensesInThisPeriod': {
    hi: 'इस अवधि में दुकान के खर्च',
    gu: 'આ સમયગાળામાં દુકાનના ખર્ચ',
  },
  'pages.reports.periodSummary.rentElectricityWagesTheShopS': {
    hi: 'किराया, बिजली, वेतन — दुकान के अपने खर्च। ये पूरी अवधि के हैं, किसी एक मरम्मत के नहीं।',
    gu: 'ભાડું, વીજળી, પગાર — દુકાનના પોતાના ખર્ચ. તે આખા સમયગાળાના છે, કોઈ એક મરામતના નહીં.',
  },
  'pages.reports.periodSummary.noShopExpensesRecordedInThis': {
    hi: 'इस अवधि में दुकान का कोई खर्च दर्ज नहीं।',
    gu: 'આ સમયગાળામાં દુકાનનો કોઈ ખર્ચ નોંધાયો નથી.',
  },
  'pages.reports.profitLoss.operatingExpenses': {
    hi: 'संचालन खर्च',
    gu: 'સંચાલન ખર્ચ',
  },
  'pages.reports.profitLoss.cashBasisAJobBilledBut': {
    hi: 'नकद आधार: बिल बना पर भुगतान न हुआ जॉब यहाँ आय नहीं है जब तक रकम न आ जाए, और दर्ज पर बिना चुकाया सप्लायर बिल लागत नहीं है जब तक चुक न जाए। दोनों तरफ़ की बाकी रकम प्राप्य और सप्लायर देय में रहती है।',
    gu: 'રોકડ ધોરણ: બિલ બન્યું પણ ચુકવણી ન થઈ હોય તે જોબ અહીં આવક નથી જ્યાં સુધી રકમ ન આવે, અને નોંધેલું પણ ન ચૂકવેલું સપ્લાયર બિલ ખર્ચ નથી જ્યાં સુધી ચૂકતે ન થાય. બંને બાજુની બાકી રકમ લેણું અને સપ્લાયર દેવુંમાં રહે છે.',
  },
  'pages.reports.serviceReports.partsItems': {
    hi: 'पुर्ज़े / आइटम',
    gu: 'પાર્ટ્સ / આઇટમ',
  },
  'pages.reports.serviceReports.totalPartsCost': {
    hi: 'पुर्ज़ों की कुल लागत',
    gu: 'પાર્ટ્સનો કુલ ખર્ચ',
  },
  'pages.reports.supplierReport.topPartsBySpend': {
    hi: 'खर्च के अनुसार मुख्य पुर्ज़े',
    gu: 'ખર્ચ પ્રમાણે મુખ્ય પાર્ટ્સ',
  },
  'pages.sales.salesInvoices.clearDates': {
    hi: 'तारीखें हटाएं',
    gu: 'તારીખો કાઢો',
  },
  'pages.secondHandDevice.createPurchase.recordASecondHandDevicePurchase': {
    hi: 'विक्रेता से सेकंड हैंड डिवाइस की खरीद दर्ज करें — तुरंत स्टॉक में जुड़ जाती है।',
    gu: 'વેચનાર પાસેથી સેકન્ડ હેન્ડ ડિવાઇસની ખરીદી નોંધો — તરત સ્ટોકમાં ઉમેરાય છે.',
  },
  'pages.secondHandDevice.createPurchase.onMobileThisOpensTheCamera': {
    hi: 'मोबाइल पर यह सीधे कैमरा खोलता है। रिकॉर्ड के लिए इस विक्रेता के साथ सहेजा जाता है।',
    gu: 'મોબાઇલ પર આ સીધો કેમેરા ખોલે છે. રેકોર્ડ માટે આ વેચનાર સાથે સચવાય છે.',
  },
  'pages.secondHandDevice.createPurchase.imeiCheckedAgainstCeirBlockedDevice': {
    hi: 'IMEI को CEIR / रोकी गई डिवाइस सूची से जाँचा गया',
    gu: 'IMEI ને CEIR / અટકાવેલી ડિવાઇસ યાદી સામે તપાસ્યું',
  },
  'pages.secondHandDevice.createPurchase.sellerDeclaredTheDeviceIsTheirs': {
    hi: 'विक्रेता ने बताया कि डिवाइस उनकी है, बेचने का हक़ है और चोरी की नहीं है',
    gu: 'વેચનારે જણાવ્યું કે ડિવાઇસ તેમની છે, વેચવાનો હક છે અને ચોરીની નથી',
  },
  'pages.secondHandDevice.createPurchase.whatYouPlanToSellThis': {
    hi: 'आप यह डिवाइस कितने में बेचना चाहते हैं। विक्रय स्क्रीन पर दिखता है।',
    gu: 'તમે આ ડિવાઇસ કેટલામાં વેચવા માગો છો. વેચાણ સ્ક્રીન પર દેખાય છે.',
  },
  'pages.secondHandDevice.devicePurchase.newPurchase': {
    hi: 'नई खरीद',
    gu: 'નવી ખરીદી',
  },
  'pages.secondHandDevice.devicePurchase.sendToRefurb': {
    hi: 'मरम्मत में भेजें',
    gu: 'રિફર્બમાં મોકલો',
  },
  'pages.secondHandDevice.devicePurchase.spentSoFarGettingThisDevice': {
    hi: 'इस डिवाइस को बिकने लायक बनाने में अब तक लगा खर्च — विक्रय के समय लाभ से घटाया जाता है।',
    gu: 'આ ડિવાઇસને વેચવા લાયક બનાવવામાં અત્યાર સુધી લાગેલો ખર્ચ — વેચાણ સમયે નફામાંથી બાદ થાય છે.',
  },
  'shared.printLabel': { hi: 'लेबल प्रिंट करें', gu: 'લેબલ પ્રિન્ટ કરો' },
  'pages.secondHandDevice.deviceSale.defaultsToWhatWasPurchasedWith': {
    hi: 'डिफ़ॉल्ट रूप से वही जो डिवाइस के साथ खरीदा गया था — कुछ रोक रहे हों या नया जोड़ रहे हों तो बदलें।',
    gu: 'ડિફોલ્ટ રીતે તે જ જે ડિવાઇસ સાથે ખરીદ્યું હતું — કંઈ રાખી લેતા હો કે નવું ઉમેરતા હો તો બદલો.',
  },
  'pages.service.actionButtons.printJobCard': {
    hi: 'जॉब कार्ड प्रिंट करें',
    gu: 'જોબ કાર્ડ પ્રિન્ટ કરો',
  },
  'pages.service.actionButtons.fieldVisit': {
    hi: 'फील्ड विज़िट',
    gu: 'ફીલ્ડ વિઝિટ',
  },
  'pages.service.actionButtons.collectPaymentNow': {
    hi: 'अभी भुगतान लें',
    gu: 'હમણાં ચુકવણી લો',
  },
  'pages.service.createJobCard.createANewServiceJobCard': {
    hi: 'ग्राहक की डिवाइस की मरम्मत और उसका हिसाब रखने के लिए नया सर्विस जॉब कार्ड बनाएं।',
    gu: 'ગ્રાહકની ડિવાઇસની મરામત અને તેનો હિસાબ રાખવા નવું સર્વિસ જોબ કાર્ડ બનાવો.',
  },
  'pages.service.createJobCard.patternDrawn': {
    hi: 'पैटर्न बना दिया',
    gu: 'પેટર્ન દોરી દીધી',
  },
  'pages.service.createJobCard.theyWillBeUploadedWhenYou': {
    hi: 'जॉब कार्ड बनाते समय ये अपलोड हो जाएंगी।',
    gu: 'જોબ કાર્ડ બનાવતી વખતે તે અપલોડ થઈ જશે.',
  },
  'pages.service.jobCards.createJobCard': {
    hi: 'जॉब कार्ड बनाएं',
    gu: 'જોબ કાર્ડ બનાવો',
  },
  'pages.service.recordCostingModal.recordActualCosting': {
    hi: 'असल लागत दर्ज करें',
    gu: 'ખરો ખર્ચ નોંધો',
  },
  'pages.service.recordCostingModal.addCostItem': {
    hi: 'लागत मद जोड़ें',
    gu: 'ખર્ચ બાબત ઉમેરો',
  },
  'pages.service.jobCosting.recordCost': { hi: 'लागत दर्ज करें', gu: 'ખર્ચ નોંધો' },
  'pages.service.serviceItems.serviceItemsAreManagedInItem': {
    hi: 'सर्विस आइटम आइटम मास्टर में प्रबंधित होते हैं। सर्विस प्रकार वाले आइटम यहाँ अपने आप दिखते हैं। आइटम जोड़ने या बदलने के लिए आइटम मास्टर का उपयोग करें।',
    gu: 'સર્વિસ આઇટમ આઇટમ માસ્ટરમાં સંભાળાય છે. સર્વિસ પ્રકારના આઇટમ અહીં આપોઆપ દેખાય છે. આઇટમ ઉમેરવા કે બદલવા આઇટમ માસ્ટર વાપરો.',
  },
  'pages.service.serviceItems.itemMaster': { hi: 'आइटम मास्टर', gu: 'આઇટમ માસ્ટર' },
  'pages.service.addOptionForm.deviceTypeSCheckMoreThan': {
    hi: 'डिवाइस प्रकार — इस ब्रांड को साझा करने के लिए एक से ज़्यादा चुनें',
    gu: 'ડિવાઇસ પ્રકાર — આ બ્રાન્ડ શેર કરવા એકથી વધુ પસંદ કરો',
  },
  'pages.settings.backupRestore.currentDatabase': {
    hi: 'मौजूदा डेटाबेस',
    gu: 'હાલનું ડેટાબેઝ',
  },
  'pages.settings.backupRestore.aBackupContainsYourCompleteCompany': {
    hi: 'बैकअप में आपकी पूरी कंपनी की जानकारी JSON स्नैपशॉट के रूप में होती है।',
    gu: 'બેકઅપમાં તમારી આખી કંપનીની માહિતી JSON સ્નેપશોટ તરીકે હોય છે.',
  },
  'pages.settings.backupRestore.dailyAutomaticBackup': {
    hi: 'रोज़ का अपने आप बैकअप',
    gu: 'રોજનું આપોઆપ બેકઅપ',
  },
  'pages.settings.backupRestore.restoreFromFile': {
    hi: 'फ़ाइल से वापस लाएं',
    gu: 'ફાઇલમાંથી પાછું લાવો',
  },
  'pages.settings.backupRestore.uploadAPreviouslyDownloadedBackupFile': {
    hi: 'पहले डाउनलोड की गई बैकअप फ़ाइल (.json) अपलोड करें। आप इसे अलग सिर्फ़-पढ़ने वाले संग्रह के रूप में वापस ला सकते हैं (सुरक्षित) या अपने चालू डेटा की जगह रख सकते हैं (खतरनाक)।',
    gu: 'પહેલાં ડાઉનલોડ કરેલી બેકઅપ ફાઇલ (.json) અપલોડ કરો. તમે તેને અલગ ફક્ત-વાંચી શકાય તેવા આર્કાઇવ તરીકે પાછું લાવી શકો (સુરક્ષિત) અથવા તમારા ચાલુ ડેટાની જગ્યાએ મૂકી શકો (ખતરનાક).',
  },
  'pages.settings.backupRestore.overwriteLiveDataDangerous': {
    hi: 'चालू डेटा बदलें (खतरनाक)',
    gu: 'ચાલુ ડેટા બદલો (ખતરનાક)',
  },
  'pages.settings.billing.everyFeatureInThisAppIs': {
    hi: 'इस ऐप की हर सुविधा हमेशा के लिए मुफ़्त है। कोई प्लान स्तर नहीं, कोई अपग्रेड सुझाव नहीं, कुछ भी चुकाना नहीं।',
    gu: 'આ એપની દરેક સુવિધા હંમેશાં મફત છે. કોઈ પ્લાન સ્તર નથી, કોઈ અપગ્રેડ સૂચન નથી, કંઈ ચૂકવવાનું નથી.',
  },
  'pages.settings.billing.editCompanyDetails': {
    hi: 'कंपनी का विवरण बदलें',
    gu: 'કંપનીની વિગતો બદલો',
  },
  'pages.settings.branchManagement.protectedSystemBranchCannotBeDeleted': {
    hi: 'सुरक्षित सिस्टम शाखा — हटाई नहीं जा सकती।',
    gu: 'સુરક્ષિત સિસ્ટમ શાખા — કાઢી શકાતી નથી.',
  },
  'pages.settings.branchManagement.aUniqueBranchCodeWillBe': {
    hi: 'नाम से एक अनोखा शाखा कोड अपने आप बन जाएगा।',
    gu: 'નામથી એક અનન્ય શાખા કોડ આપોઆપ બની જશે.',
  },
  'pages.settings.companySettings.defaultCompany': {
    hi: 'डिफ़ॉल्ट कंपनी',
    gu: 'ડિફોલ્ટ કંપની',
  },
  'pages.settings.companySettings.switchToThisCompany': {
    hi: 'इस कंपनी पर जाएं',
    gu: 'આ કંપની પર જાઓ',
  },
  'pages.settings.companySettings.protectedCannotDisableDelete': {
    hi: 'सुरक्षित: बंद / हटाया नहीं जा सकता',
    gu: 'સુરક્ષિત: બંધ / કાઢી શકાતું નથી',
  },
  'pages.settings.companySettings.addCompany': {
    hi: 'कंपनी जोड़ें',
    gu: 'કંપની ઉમેરો',
  },
  'pages.settings.companySettings.companyPreferencesActiveCompany': {
    hi: 'कंपनी की पसंद (चालू कंपनी)',
    gu: 'કંપનીની પસંદ (ચાલુ કંપની)',
  },
  'pages.settings.companySettings.currentlyActive': {
    hi: 'अभी चालू',
    gu: 'હાલ ચાલુ',
  },
  'pages.settings.companySettings.defaultCompanyCannotBeDisabledOr': {
    hi: 'डिफ़ॉल्ट कंपनी — बंद या हटाई नहीं जा सकती।',
    gu: 'ડિફોલ્ટ કંપની — બંધ કે કાઢી શકાતી નથી.',
  },
  'pages.settings.financialYears.makeCurrent': {
    hi: 'वर्तमान बनाएं',
    gu: 'ચાલુ બનાવો',
  },
  'pages.settings.financialYears.thisIsTheCurrentlyActiveFinancial': {
    hi: 'यह अभी सक्रिय वित्तीय वर्ष है। सभी नए लेन-देन इसी अवधि में दर्ज होंगे। एक समय पर सिर्फ़ एक वित्तीय वर्ष सक्रिय रह सकता है।',
    gu: 'આ હાલ સક્રિય નાણાકીય વર્ષ છે. બધા નવા વ્યવહાર આ જ સમયગાળામાં નોંધાશે. એક સમયે ફક્ત એક નાણાકીય વર્ષ સક્રિય રહી શકે.',
  },
  'pages.settings.financialYears.thisYearIsClosedExistingRecords': {
    hi: 'यह वर्ष बंद है। पुराने रिकॉर्ड पढ़े जा सकते हैं; इसे कार्रवाई मेन्यू से फिर खोला जाता है।',
    gu: 'આ વર્ષ બંધ છે. જૂના રેકોર્ડ વાંચી શકાય છે; તેને ક્રિયા મેન્યુમાંથી ફરી ખોલાય છે.',
  },
  'shared.setAsDefault': { hi: 'डिफ़ॉल्ट बनाएं', gu: 'ડિફોલ્ટ બનાવો' },
  'pages.settings.designer.exportAsJson': {
    hi: 'JSON के रूप में एक्सपोर्ट करें',
    gu: 'JSON તરીકે એક્સપોર્ટ કરો',
  },
  'pages.settings.designer.resetToDefault': {
    hi: 'डिफ़ॉल्ट पर लौटें',
    gu: 'ડિફોલ્ટ પર પાછા જાઓ',
  },
  'pages.settings.designer.showCaption': {
    hi: 'शीर्षक दिखाएं',
    gu: 'મથાળું બતાવો',
  },
  'pages.settings.designer.appliesAtPrintTimePerRecord': {
    hi: 'प्रिंट के समय, हर रिकॉर्ड पर लागू होता है — GSTIN जैसी पंक्ति के लिए उपयोगी जो सिर्फ़ कुछ दुकानों के पास होती है।',
    gu: 'પ્રિન્ટ સમયે, દરેક રેકોર્ડ પર લાગુ થાય છે — GSTIN જેવી પંક્તિ માટે ઉપયોગી જે ફક્ત કેટલીક દુકાનો પાસે હોય છે.',
  },
  'pages.settings.pageSetupDialog.duplicateCopy': {
    hi: 'दूसरी नकल',
    gu: 'બીજી નકલ',
  },
  'pages.settings.pageSetupDialog.savedWithTheTemplateButOnly': {
    hi: 'टेम्पलेट के साथ सहेजा जाता है, पर लागू सिर्फ़ प्रिंट एजेंट करता है। ये प्रिंटर फ़र्मवेयर कमांड हैं — इस ब्राउज़र से प्रिंट करने पर उसका अपना डायलॉग चलता है और ये अनदेखे रह जाते हैं।',
    gu: 'ટેમ્પલેટ સાથે સચવાય છે, પણ લાગુ ફક્ત પ્રિન્ટ એજન્ટ કરે છે. આ પ્રિન્ટર ફર્મવેર કમાન્ડ છે — આ બ્રાઉઝરથી પ્રિન્ટ કરતાં તેનો પોતાનો ડાયલોગ ચાલે છે અને આ અવગણાય છે.',
  },
  'pages.settings.printDevicesDialog.enterThisCodeInThePrint': {
    hi: 'दुकान के PC पर प्रिंट एजेंट में यह कोड डालें:',
    gu: 'દુકાનના PC પર પ્રિન્ટ એજન્ટમાં આ કોડ નાખો:',
  },
  'pages.settings.printDevicesDialog.itWillStopPrintingTheNext': {
    hi: 'अगली बार जुड़ते ही यह प्रिंट करना बंद कर देगा। आप इसे नए कोड से दोबारा जोड़ सकते हैं।',
    gu: 'આગલી વાર જોડાતાં જ તે પ્રિન્ટ કરવાનું બંધ કરી દેશે. તમે તેને નવા કોડથી ફરી જોડી શકો છો.',
  },
  'pages.settings.printDevicesDialog.shopPcsRunningThePrintAgent': {
    hi: 'प्रिंट एजेंट चला रहे दुकान के PC। इस ब्राउज़र से बिल और लेबल प्रिंट कराने के लिए किसी एक को जोड़ें।',
    gu: 'પ્રિન્ટ એજન્ટ ચલાવતા દુકાનના PC. આ બ્રાઉઝરથી બિલ અને લેબલ પ્રિન્ટ કરાવવા કોઈ એકને જોડો.',
  },
  'pages.settings.printDevicesDialog.noPrintDevicePairedYet': {
    hi: 'अभी कोई प्रिंट डिवाइस नहीं जुड़ी।',
    gu: 'હજી કોઈ પ્રિન્ટ ડિવાઇસ જોડાયેલી નથી.',
  },
  'pages.settings.printFormats.importTemplate': {
    hi: 'टेम्पलेट इम्पोर्ट करें',
    gu: 'ટેમ્પલેટ ઇમ્પોર્ટ કરો',
  },
  'pages.settings.printFormats.printDevices': {
    hi: 'प्रिंट डिवाइस',
    gu: 'પ્રિન્ટ ડિવાઇસ',
  },
  'pages.settings.printFormats.newTemplate': {
    hi: 'नया टेम्पलेट',
    gu: 'નવું ટેમ્પલેટ',
  },
  'pages.settings.whatsapp.prefixedToACustomerS10': {
    hi: 'WhatsApp खोलने से पहले ग्राहक के 10 अंकों के मोबाइल से पहले लगाया जाता है।',
    gu: 'WhatsApp ખોલતાં પહેલાં ગ્રાહકના 10 અંકના મોબાઇલ પહેલાં લગાવાય છે.',
  },
  'pages.settings.behaviorSubtab.whichPopupOpensAutomaticallyAfterAn': {
    hi: 'कोई कार्रवाई पूरी होने के बाद कौन-सा पॉपअप अपने आप खुलता है — कोई अतिरिक्त क्लिक नहीं। सब डिफ़ॉल्ट रूप से बंद।',
    gu: 'કોઈ ક્રિયા પૂરી થયા પછી કયું પોપઅપ આપોઆપ ખૂલે છે — કોઈ વધારાનું ક્લિક નહીં. બધું ડિફોલ્ટ રીતે બંધ.',
  },
  'pages.settings.formBuilderTab.noTemplatesSavedYet': {
    hi: 'अभी कोई टेम्पलेट सहेजा नहीं',
    gu: 'હજી કોઈ ટેમ્પલેટ સાચવ્યું નથી',
  },
  'pages.settings.formBuilderTab.saveAsTemplate': {
    hi: 'टेम्पलेट के रूप में सहेजें',
    gu: 'ટેમ્પલેટ તરીકે સાચવો',
  },
  'pages.settings.formBuilderTab.discardChanges': {
    hi: 'बदलाव छोड़ दें',
    gu: 'ફેરફાર છોડી દો',
  },
  'pages.settings.formBuilderTab.useTheIconsOnEachField': {
    hi: 'नीचे हर फ़ील्ड पर बने चिह्नों से उसे सेट करें।',
    gu: 'નીચે દરેક ફીલ્ડ પરના ચિહ્નોથી તેને ગોઠવો.',
  },
  'pages.settings.permissionsSubtab.statusFilter': {
    hi: 'स्थिति फ़िल्टर',
    gu: 'સ્થિતિ ફિલ્ટર',
  },
  'pages.settings.permissionsSubtab.tickABoxThisRoleCan': {
    hi: 'बॉक्स पर निशान = जॉब उस स्थिति में होने पर यह भूमिका वह कार्रवाई कर सकती है।',
    gu: 'બોક્સ પર નિશાન = જોબ તે સ્થિતિમાં હોય ત્યારે આ ભૂમિકા તે ક્રિયા કરી શકે.',
  },
  'pages.settings.rolePermissionsTab.howItWorks': {
    hi: 'यह कैसे काम करता है',
    gu: 'આ કેવી રીતે કામ કરે છે',
  },
  'pages.settings.rolePermissionsTab.configuredRoles': {
    hi: 'कॉन्फ़िगर की गई भूमिकाएं',
    gu: 'કોન્ફિગર કરેલી ભૂમિકાઓ',
  },
  'pages.settings.usersSubtab.whoCanBeAssignedJobsAnd': {
    hi: 'किसे जॉब सौंपे जा सकते हैं और वे किसे आगे देते हैं',
    gu: 'કોને જોબ સોંપી શકાય અને તે કોને આગળ આપે',
  },
  'pages.settings.usersSubtab.assignToRoles': {
    hi: 'सौंपने वाली भूमिकाएं',
    gu: 'સોંપણી ભૂમિકાઓ',
  },
  'pages.settings.usersSubtab.handoverRoles': {
    hi: 'आगे देने वाली भूमिकाएं',
    gu: 'સોંપી દેનાર ભૂમિકાઓ',
  },
  'pages.settings.usersSubtab.whenAnActionHappensShouldThe': {
    hi: 'कोई कार्रवाई होने पर उपयोगकर्ता चुने कि किसने की? बंद = लॉग इन उपयोगकर्ता अपने आप दर्ज होता है।',
    gu: 'કોઈ ક્રિયા થાય ત્યારે વપરાશકર્તા પસંદ કરે કે કોણે કરી? બંધ = લોગ ઇન વપરાશકર્તા આપોઆપ નોંધાય છે.',
  },
  'pages.settings.usersSubtab.loggedInUserIsRecordedAutomatically': {
    hi: 'लॉग इन उपयोगकर्ता अपने आप दर्ज होता है',
    gu: 'લોગ ઇન વપરાશકર્તા આપોઆપ નોંધાય છે',
  },
  'pages.settings.workflowDesigner.controlExactlyWhatEachRoleCan': {
    hi: 'तय करें कि हर जॉब स्थिति पर हर भूमिका ठीक क्या देख और कर सकती है।',
    gu: 'નક્કી કરો કે દરેક જોબ સ્થિતિ પર દરેક ભૂમિકા બરાબર શું જોઈ અને કરી શકે.',
  },
  'pages.completeSetup.completeSetup.signOutAndStartOver': {
    hi: 'लॉग आउट करके फिर से शुरू करें',
    gu: 'લોગ આઉટ કરીને ફરી શરૂ કરો',
  },
  'pages.forgotPassword.forgotPassword.backToLogIn': {
    hi: 'लॉग इन पर वापस',
    gu: 'લોગ ઇન પર પાછા',
  },
  'pages.forgotPassword.forgotPassword.ifAnAccountExistsForThat': {
    hi: 'अगर उस पते का कोई खाता है, तो बदलने की लिंक भेज दी गई है।',
    gu: 'જો તે સરનામાનું કોઈ ખાતું હોય, તો બદલવાની લિંક મોકલી દેવાઈ છે.',
  },
  'pages.login.login.signUpFree': { hi: 'मुफ़्त साइन अप करें', gu: 'મફત સાઇન અપ કરો' },
  'pages.login.login.forgotPassword': { hi: 'पासवर्ड भूल गए?', gu: 'પાસવર્ડ ભૂલી ગયા?' },
  'pages.landing.landing.manageRepairsFromCustomerIntakeTo': {
    hi: 'ग्राहक से डिवाइस लेने से सौंपने तक मरम्मत संभालें — जॉब कार्ड, तकनीशियन वर्कफ़्लो, ग्राहक सूचना, बिलिंग, भुगतान और वारंटी, सब एक जुड़े सिस्टम में।',
    gu: 'ગ્રાહક પાસેથી ડિવાઇસ લેવાથી આપવા સુધી મરામત સંભાળો — જોબ કાર્ડ, ટેકનિશિયન વર્કફ્લો, ગ્રાહક સૂચના, બિલિંગ, ચુકવણી અને વોરંટી, બધું એક જોડાયેલી સિસ્ટમમાં.',
  },
  'shared.getStarted': { hi: 'शुरू करें', gu: 'શરૂ કરો' },
  'pages.landing.landing.bookADemo': { hi: 'डेमो बुक करें', gu: 'ડેમો બુક કરો' },
  'pages.landing.landing.noCardRequiredFreeForeverFree': {
    hi: 'कार्ड की ज़रूरत नहीं · हमेशा मुफ़्त · मुफ़्त डेटा माइग्रेशन',
    gu: 'કાર્ડની જરૂર નથી · હંમેશાં મફત · મફત ડેટા માઇગ્રેશન',
  },
  'pages.landing.landing.notAnotherBillingToolAComplete': {
    hi: 'एक और बिलिंग टूल नहीं। आपकी मरम्मत की दुकान चलाने का पूरा सिस्टम।',
    gu: 'બીજું બિલિંગ ટૂલ નહીં. તમારી મરામતની દુકાન ચલાવવાની સંપૂર્ણ સિસ્ટમ.',
  },
  'pages.landing.landing.fromIntakeToDeliveryOneWorkflow': {
    hi: 'डिवाइस लेने से सौंपने तक, एक ही वर्कफ़्लो',
    gu: 'ડિવાઇસ લેવાથી આપવા સુધી, એક જ વર્કફ્લો',
  },
  'pages.landing.landing.everyJobFollowsTheSameConnected': {
    hi: 'हर जॉब उसी जुड़े रास्ते पर चलता है — बीच में कोई स्प्रेडशीट नहीं।',
    gu: 'દરેક જોબ તે જ જોડાયેલા રસ્તે ચાલે છે — વચ્ચે કોઈ સ્પ્રેડશીટ નહીં.',
  },
}
