// GENERATED by tools/data/build-permission-catalogue.cjs — do not edit by hand.
//
// Source: data/permotion-sample.json (197 permissions across 10 modules and
// 47 features).
//
// The keys are the reference system's own — `SALES_INVOICES_CREATE`, not `sales.invoices.create`
// — because a role's `actionPermissions` map is a storage format, and two systems that spell it
// differently cannot read each other's roles.

export type PermissionKind = 'module' | 'crud' | 'custom'

export interface PermissionSpec {
  /** The stored key, e.g. `SERVICE_JOB_CARDS_ASSIGN`. */
  key: string
  /** The reference's own wording, e.g. "Assign Job Card". */
  label: string
  /** `view`, `create`, `export`, `assign`… — what the permission lets you do. */
  action: string
  kind: PermissionKind
}

export interface PermissionFeatureSpec {
  /** The nav leaf slug this feature is reached through — see `nav.ts`. */
  navSlug: string
  /** What the reference calls it, kept so a key can be traced back to the export. */
  refSlug: string
  permissions: PermissionSpec[]
}

export interface PermissionModuleSpec {
  sectionKey: string
  label: string
  /** Every module has exactly one "access this module" permission. */
  moduleAccess: PermissionSpec
  features: PermissionFeatureSpec[]
}

export const PERMISSION_CATALOGUE: PermissionModuleSpec[] = [
  {
    sectionKey: 'administration',
    label: 'Administration',
    moduleAccess: {
      key: 'ADMIN_MODULE_ACCESS',
      label: 'Access Administration Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'users',
        refSlug: 'users',
        permissions: [
          {
            key: 'ADMINISTRATION_USERS_VIEW',
            label: 'View User Management',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_USERS_CREATE',
            label: 'Create User Management',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_USERS_UPDATE',
            label: 'Update User Management',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_USERS_DELETE',
            label: 'Delete User Management',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_USERS_RESET_PASSWORD',
            label: 'Reset Password',
            action: 'reset-password',
            kind: 'custom',
          },
          {
            key: 'ADMINISTRATION_USERS_CHANGE_SELF_PASSWORD',
            label: 'Change Self Password',
            action: 'change-self-password',
            kind: 'custom',
          },
          {
            key: 'ADMINISTRATION_USERS_STATUS_CHANGE',
            label: 'Status Change User',
            action: 'status-change',
            kind: 'custom',
          },
          {
            key: 'ADMINISTRATION_USERS_IMPERSONATE',
            label: 'Impersonate User',
            action: 'impersonate',
            kind: 'custom',
          },
          {
            key: 'ADMINISTRATION_USERS_TOGGLE_IP_RESTRICTION',
            label: 'Toggle IP Restriction',
            action: 'toggle-ip-restriction',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'roles',
        refSlug: 'roles',
        permissions: [
          {
            key: 'ADMINISTRATION_ROLES_VIEW',
            label: 'View Role Management',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_ROLES_CREATE',
            label: 'Create Role Management',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_ROLES_UPDATE',
            label: 'Update Role Management',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_ROLES_DELETE',
            label: 'Delete Role Management',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_ROLES_ASSIGN_PERMISSIONS',
            label: 'Assign Role Permissions',
            action: 'assign-permissions',
            kind: 'custom',
          },
          {
            key: 'ADMINISTRATION_ROLES_ASSIGN_MENUS',
            label: 'Assign Role Menus',
            action: 'assign-menus',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'sessions',
        refSlug: 'sessions',
        permissions: [
          {
            key: 'ADMINISTRATION_SESSIONS_VIEW',
            label: 'View Active Sessions',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_SESSIONS_TERMINATE',
            label: 'Terminate Session',
            action: 'terminate',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'ip-whitelist',
        refSlug: 'ip-whitelist',
        permissions: [
          {
            key: 'ADMINISTRATION_IP_WHITELIST_VIEW',
            label: 'View IP Whitelist',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_IP_WHITELIST_CREATE',
            label: 'Create IP Whitelist',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_IP_WHITELIST_UPDATE',
            label: 'Update IP Whitelist',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_IP_WHITELIST_DELETE',
            label: 'Delete IP Whitelist',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'login-report',
        refSlug: 'login-report',
        permissions: [
          {
            key: 'ADMINISTRATION_LOGIN_REPORT_VIEW',
            label: 'View Login Report',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_LOGIN_REPORT_EXPORT',
            label: 'Export Login Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'audit',
        refSlug: 'system-audit',
        permissions: [
          {
            key: 'ADMINISTRATION_SYSTEM_AUDIT_VIEW',
            label: 'View System Audit',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'ADMINISTRATION_SYSTEM_AUDIT_EXPORT',
            label: 'Export Logs',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'settings',
    label: 'Settings',
    moduleAccess: {
      key: 'SETTINGS_MODULE_ACCESS',
      label: 'Access Settings Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'branches',
        refSlug: 'branches',
        permissions: [
          {
            key: 'SETTINGS_BRANCHES_VIEW',
            label: 'View Branch Management',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_BRANCHES_CREATE',
            label: 'Create Branch Management',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_BRANCHES_UPDATE',
            label: 'Update Branch Management',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_BRANCHES_DELETE',
            label: 'Delete Branch Management',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'workflow',
        refSlug: 'workflow-designer',
        permissions: [
          {
            key: 'SETTINGS_WORKFLOW_DESIGNER_VIEW',
            label: 'View Workflow Designer',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_WORKFLOW_DESIGNER_MANAGE',
            label: 'Manage Workflow Config',
            action: 'manage',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_WORKFLOW_DESIGNER_VIEW_FORM_BUILDER',
            label: 'View Form Builder',
            action: 'view_form_builder',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_WORKFLOW_DESIGNER_EDIT_FORM_BUILDER',
            label: 'Edit Form Builder',
            action: 'edit_form_builder',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_WORKFLOW_DESIGNER_PUBLISH_FORM_BUILDER',
            label: 'Publish Form Builder Configuration',
            action: 'publish_form_builder',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'company',
        refSlug: 'company',
        permissions: [
          {
            key: 'SETTINGS_COMPANY_VIEW',
            label: 'View Company Settings',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_COMPANY_CREATE',
            label: 'Create Company Settings',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_COMPANY_UPDATE',
            label: 'Update Company Settings',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_COMPANY_DELETE',
            label: 'Delete Company Settings',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_COMPANY_RESTORE',
            label: 'Restore Company Settings',
            action: 'restore',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_COMPANY_SET_DEFAULT',
            label: 'Set Default Company',
            action: 'set_default',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_COMPANY_STATUS',
            label: 'Enable / Disable Company',
            action: 'status',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'financial-years',
        refSlug: 'financial-years',
        permissions: [
          {
            key: 'SETTINGS_FINANCIAL_YEARS_VIEW',
            label: 'View Financial Years',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_FINANCIAL_YEARS_CREATE',
            label: 'Create Financial Years',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_FINANCIAL_YEARS_UPDATE',
            label: 'Update Financial Years',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_FINANCIAL_YEARS_DELETE',
            label: 'Delete Financial Years',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_FINANCIAL_YEARS_ACTIVATE',
            label: 'Activate Financial Year',
            action: 'activate',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_FINANCIAL_YEARS_CLOSE',
            label: 'Close Financial Year',
            action: 'close',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_FINANCIAL_YEARS_ROLLBACK_CLOSE',
            label: 'Reopen a Closed Financial Year',
            action: 'rollback-close',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'billing',
        refSlug: 'billing',
        permissions: [
          {
            key: 'SETTINGS_BILLING_VIEW',
            label: 'View Billing & Subscription',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_BILLING_UPDATE',
            label: 'Update Billing & Subscription',
            action: 'update',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'print-formats',
        refSlug: 'print-formats',
        permissions: [
          {
            key: 'SETTINGS_PRINT_FORMATS_VIEW',
            label: 'View Print Formats',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_CREATE',
            label: 'Create Print Formats',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_UPDATE',
            label: 'Update Print Formats',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_DELETE',
            label: 'Delete Print Formats',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_DUPLICATE',
            label: 'Duplicate Template',
            action: 'duplicate',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_SET_DEFAULT',
            label: 'Set Default Template',
            action: 'set_default',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_RESTORE_VERSION',
            label: 'Restore Template Version',
            action: 'restore_version',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_PRINT_FORMATS_BULK_PRINT',
            label: 'Bulk Print Labels',
            action: 'bulk_print',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'whatsapp',
        refSlug: 'whatsapp-settings',
        permissions: [
          {
            key: 'SETTINGS_WHATSAPP_SETTINGS_VIEW',
            label: 'View WhatsApp',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_WHATSAPP_SETTINGS_CREATE',
            label: 'Create WhatsApp',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_WHATSAPP_SETTINGS_UPDATE',
            label: 'Update WhatsApp',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_WHATSAPP_SETTINGS_DELETE',
            label: 'Delete WhatsApp',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'backup',
        refSlug: 'backup',
        permissions: [
          {
            key: 'SETTINGS_BACKUP_VIEW',
            label: 'View Backup & Restore',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SETTINGS_BACKUP_BACKUP',
            label: 'Create Backup',
            action: 'backup',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_BACKUP_RESTORE',
            label: 'Restore Backup',
            action: 'restore',
            kind: 'custom',
          },
          {
            key: 'SETTINGS_BACKUP_DOWNLOAD',
            label: 'Download Backup',
            action: 'download',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'service',
    label: 'Service',
    moduleAccess: {
      key: 'SERVICE_MODULE_ACCESS',
      label: 'Access Service Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'job-cards',
        refSlug: 'job-cards',
        permissions: [
          {
            key: 'SERVICE_JOB_CARDS_VIEW',
            label: 'View Job Cards',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_CARDS_CREATE',
            label: 'Create Job Cards',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_CARDS_UPDATE',
            label: 'Update Job Cards',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_CARDS_DELETE',
            label: 'Delete Job Cards',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_CARDS_RESTORE',
            label: 'Restore Job Cards',
            action: 'restore',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_CARDS_ASSIGN',
            label: 'Assign Technician',
            action: 'assign',
            kind: 'custom',
          },
          {
            key: 'SERVICE_JOB_CARDS_CLOSE',
            label: 'Close Job Card',
            action: 'close',
            kind: 'custom',
          },
          {
            key: 'SERVICE_JOB_CARDS_CANCEL',
            label: 'Cancel Job Card',
            action: 'cancel',
            kind: 'custom',
          },
          {
            key: 'SERVICE_JOB_CARDS_INVOICE',
            label: 'Convert To Invoice',
            action: 'invoice',
            kind: 'custom',
          },
          {
            key: 'SERVICE_JOB_CARDS_REPEAT',
            label: 'Repeat Job Card',
            action: 'repeat',
            kind: 'custom',
          },
          {
            key: 'SERVICE_JOB_CARDS_PRINT_RECEIPT',
            label: 'Print Receipt',
            action: 'print_receipt',
            kind: 'custom',
          },
          {
            key: 'SERVICE_JOB_CARDS_PRINT_LABEL',
            label: 'Print Label',
            action: 'print_label',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'options',
        refSlug: 'service-options',
        permissions: [
          {
            key: 'SERVICE_SERVICE_OPTIONS_VIEW',
            label: 'View Service Options',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SERVICE_SERVICE_OPTIONS_MANAGE',
            label: 'Manage Options (Create / Edit / Delete)',
            action: 'manage',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'costing',
        refSlug: 'job-costing',
        permissions: [
          {
            key: 'SERVICE_JOB_COSTING_VIEW',
            label: 'View Job Costing',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_COSTING_CREATE',
            label: 'Create Job Costing',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_COSTING_UPDATE',
            label: 'Update Job Costing',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SERVICE_JOB_COSTING_DELETE',
            label: 'Delete Job Costing',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'items',
        refSlug: 'service-items',
        permissions: [
          {
            key: 'SERVICE_SERVICE_ITEMS_VIEW',
            label: 'View Service Items',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SERVICE_SERVICE_ITEMS_CREATE',
            label: 'Create Service Items',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SERVICE_SERVICE_ITEMS_UPDATE',
            label: 'Update Service Items',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SERVICE_SERVICE_ITEMS_DELETE',
            label: 'Delete Service Items',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'masters',
    label: 'Masters',
    moduleAccess: {
      key: 'MASTERS_MODULE_ACCESS',
      label: 'Access Masters Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'uom',
        refSlug: 'uom',
        permissions: [
          {
            key: 'MASTERS_UOM_VIEW',
            label: 'View Units of Measure',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_UOM_CREATE',
            label: 'Create Units of Measure',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_UOM_UPDATE',
            label: 'Update Units of Measure',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_UOM_DELETE',
            label: 'Delete Units of Measure',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'MASTERS_UOM_RESTORE',
            label: 'Restore Units of Measure',
            action: 'restore',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'item-categories',
        refSlug: 'categories',
        permissions: [
          {
            key: 'MASTERS_CATEGORIES_VIEW',
            label: 'View Item Categories',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_CATEGORIES_CREATE',
            label: 'Create Item Categories',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_CATEGORIES_UPDATE',
            label: 'Update Item Categories',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_CATEGORIES_DELETE',
            label: 'Delete Item Categories',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'MASTERS_CATEGORIES_RESTORE',
            label: 'Restore Item Categories',
            action: 'restore',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'attributes',
        refSlug: 'attributes',
        permissions: [
          {
            key: 'MASTERS_ATTRIBUTES_VIEW',
            label: 'View Attributes',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ATTRIBUTES_CREATE',
            label: 'Create Attributes',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ATTRIBUTES_UPDATE',
            label: 'Update Attributes',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ATTRIBUTES_DELETE',
            label: 'Delete Attributes',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'items',
        refSlug: 'items',
        permissions: [
          {
            key: 'MASTERS_ITEMS_VIEW',
            label: 'View Item Master',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ITEMS_CREATE',
            label: 'Create Item Master',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ITEMS_UPDATE',
            label: 'Update Item Master',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ITEMS_DELETE',
            label: 'Delete Item Master',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ITEMS_RESTORE',
            label: 'Restore Item Master',
            action: 'restore',
            kind: 'crud',
          },
          {
            key: 'MASTERS_ITEMS_IMPORT',
            label: 'Import Items',
            action: 'import',
            kind: 'custom',
          },
          {
            key: 'MASTERS_ITEMS_EXPORT',
            label: 'Export Items',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'payment-modes',
        refSlug: 'payment-modes',
        permissions: [
          {
            key: 'MASTERS_PAYMENT_MODES_VIEW',
            label: 'View Payment Modes',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PAYMENT_MODES_CREATE',
            label: 'Create Payment Modes',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PAYMENT_MODES_UPDATE',
            label: 'Update Payment Modes',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PAYMENT_MODES_DELETE',
            label: 'Delete Payment Modes',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'party-categories',
        refSlug: 'party-categories',
        permissions: [
          {
            key: 'MASTERS_PARTY_CATEGORIES_VIEW',
            label: 'View Party Categories',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTY_CATEGORIES_CREATE',
            label: 'Create Party Categories',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTY_CATEGORIES_UPDATE',
            label: 'Update Party Categories',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTY_CATEGORIES_DELETE',
            label: 'Delete Party Categories',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTY_CATEGORIES_RESTORE',
            label: 'Restore Party Categories',
            action: 'restore',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'parties',
        refSlug: 'parties',
        permissions: [
          {
            key: 'MASTERS_PARTIES_VIEW',
            label: 'View Parties',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTIES_CREATE',
            label: 'Create Parties',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTIES_UPDATE',
            label: 'Update Parties',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTIES_DELETE',
            label: 'Delete Parties',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTIES_RESTORE',
            label: 'Restore Parties',
            action: 'restore',
            kind: 'crud',
          },
          {
            key: 'MASTERS_PARTIES_LEDGER_VIEW',
            label: 'View Party Ledger',
            action: 'ledger_view',
            kind: 'custom',
          },
          {
            key: 'MASTERS_PARTIES_OUTSTANDING_VIEW',
            label: 'View Outstanding',
            action: 'outstanding_view',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'second-hand-device',
    label: 'Second Hand Device',
    moduleAccess: {
      key: 'SECOND_HAND_DEVICE_MODULE_ACCESS',
      label: 'Access Second Hand Device Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'purchase',
        refSlug: 'device-purchase',
        permissions: [
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_VIEW',
            label: 'View Device Purchase',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_CREATE',
            label: 'Create Device Purchase',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_UPDATE',
            label: 'Update Device Purchase',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_CANCEL',
            label: 'Return Device to Seller',
            action: 'cancel',
            kind: 'custom',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_PRINT',
            label: 'Print Purchase Receipt',
            action: 'print',
            kind: 'custom',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_EXPORT',
            label: 'Export Device Purchases',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'sale',
        refSlug: 'device-sale',
        permissions: [
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_VIEW',
            label: 'View Device Sale',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_CREATE',
            label: 'Create Device Sale',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_CANCEL',
            label: 'Cancel Sale',
            action: 'cancel',
            kind: 'custom',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_PRINT',
            label: 'Print Sale Invoice',
            action: 'print',
            kind: 'custom',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_EXPORT',
            label: 'Export Available Devices',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'stock',
        refSlug: 'device-stock',
        permissions: [
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_STOCK_VIEW',
            label: 'View Device Stock',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_STOCK_EXPORT',
            label: 'Export Device Stock',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'purchase-register',
        refSlug: 'device-purchase-register',
        permissions: [
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_REGISTER_VIEW',
            label: 'View Purchase Register',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_PURCHASE_REGISTER_EXPORT',
            label: 'Export Purchase Register',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'sale-register',
        refSlug: 'device-sale-register',
        permissions: [
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_REGISTER_VIEW',
            label: 'View Sale Register',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SECOND_HAND_DEVICE_DEVICE_SALE_REGISTER_EXPORT',
            label: 'Export Sale Register',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'finance',
    label: 'Finance',
    moduleAccess: {
      key: 'FINANCE_MODULE_ACCESS',
      label: 'Access Finance Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'receipts',
        refSlug: 'receipts',
        permissions: [
          {
            key: 'FINANCE_RECEIPTS_VIEW',
            label: 'View Receipts & Payments',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_RECEIPTS_CREATE',
            label: 'Create Receipts & Payments',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'FINANCE_RECEIPTS_VOID',
            label: 'Void Receipt',
            action: 'void',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'ledger',
        refSlug: 'ledger',
        permissions: [
          {
            key: 'FINANCE_LEDGER_VIEW',
            label: 'View Party Ledger',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_LEDGER_EXPORT',
            label: 'Export Ledger',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'cashbook',
        refSlug: 'cashbook',
        permissions: [
          {
            key: 'FINANCE_CASHBOOK_VIEW',
            label: 'View Cash Book',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_CASHBOOK_EXPORT',
            label: 'Export Cash Book',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'receivables',
        refSlug: 'receivables',
        permissions: [
          {
            key: 'FINANCE_RECEIVABLES_VIEW',
            label: 'View Receivables',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_RECEIVABLES_EXPORT',
            label: 'Export Receivables',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'payables',
        refSlug: 'payables',
        permissions: [
          {
            key: 'FINANCE_PAYABLES_VIEW',
            label: 'View Customer Payables',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_PAYABLES_EXPORT',
            label: 'Export Payables',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'supplier-payables',
        refSlug: 'supplier-payables',
        permissions: [
          {
            key: 'FINANCE_SUPPLIER_PAYABLES_VIEW',
            label: 'View Supplier Payables',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_SUPPLIER_PAYABLES_EXPORT',
            label: 'Export Supplier Payables',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'expenses',
        refSlug: 'expenses',
        permissions: [
          {
            key: 'FINANCE_EXPENSES_VIEW',
            label: 'View Expenses',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'FINANCE_EXPENSES_CREATE',
            label: 'Create Expenses',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'FINANCE_EXPENSES_CANCEL',
            label: 'Cancel Expense',
            action: 'cancel',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'reports',
    label: 'Reports',
    moduleAccess: {
      key: 'REPORTS_MODULE_ACCESS',
      label: 'Access Reports Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'service',
        refSlug: 'service-reports',
        permissions: [
          {
            key: 'REPORTS_SERVICE_REPORTS_VIEW',
            label: 'View Service Reports',
            action: 'view',
            kind: 'crud',
          },
        ],
      },
      {
        navSlug: 'pnl',
        refSlug: 'profit-loss',
        permissions: [
          {
            key: 'REPORTS_PROFIT_LOSS_VIEW',
            label: 'View Profit & Loss',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'REPORTS_PROFIT_LOSS_EXPORT',
            label: 'Export Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'job-profit',
        refSlug: 'pnl-report',
        permissions: [
          {
            key: 'REPORTS_PNL_REPORT_VIEW',
            label: 'View Job-wise Profit',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'REPORTS_PNL_REPORT_EXPORT',
            label: 'Export Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'supplier',
        refSlug: 'supplier-report',
        permissions: [
          {
            key: 'REPORTS_SUPPLIER_REPORT_VIEW',
            label: 'View Supplier Report',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'REPORTS_SUPPLIER_REPORT_EXPORT',
            label: 'Export Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'technician',
        refSlug: 'technician-report',
        permissions: [
          {
            key: 'REPORTS_TECHNICIAN_REPORT_VIEW',
            label: 'View Technician Report',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'REPORTS_TECHNICIAN_REPORT_EXPORT',
            label: 'Export Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'period-summary',
        refSlug: 'period-summary',
        permissions: [
          {
            key: 'REPORTS_PERIOD_SUMMARY_VIEW',
            label: 'View Period Summary',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'REPORTS_PERIOD_SUMMARY_EXPORT',
            label: 'Export Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
      {
        navSlug: 'field-visits',
        refSlug: 'field-visit-report',
        permissions: [
          {
            key: 'REPORTS_FIELD_VISIT_REPORT_VIEW',
            label: 'View Field Visit Report',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'REPORTS_FIELD_VISIT_REPORT_EXPORT',
            label: 'Export Report',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'sales',
    label: 'Sales',
    moduleAccess: {
      key: 'SALES_MODULE_ACCESS',
      label: 'Access Sales Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'invoices',
        refSlug: 'invoices',
        permissions: [
          {
            key: 'SALES_INVOICES_VIEW',
            label: 'View Sales Invoices',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'SALES_INVOICES_CREATE',
            label: 'Create Sales Invoices',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'SALES_INVOICES_UPDATE',
            label: 'Update Sales Invoices',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'SALES_INVOICES_DELETE',
            label: 'Delete Sales Invoices',
            action: 'delete',
            kind: 'crud',
          },
          {
            key: 'SALES_INVOICES_APPROVE',
            label: 'Approve Invoice',
            action: 'approve',
            kind: 'custom',
          },
          {
            key: 'SALES_INVOICES_CANCEL',
            label: 'Cancel Invoice',
            action: 'cancel',
            kind: 'custom',
          },
          {
            key: 'SALES_INVOICES_PAYMENT',
            label: 'Record Payment',
            action: 'payment',
            kind: 'custom',
          },
          {
            key: 'SALES_INVOICES_PRINT',
            label: 'Print Invoice',
            action: 'print',
            kind: 'custom',
          },
          {
            key: 'SALES_INVOICES_EMAIL',
            label: 'Email Invoice',
            action: 'email',
            kind: 'custom',
          },
          {
            key: 'SALES_INVOICES_EXPORT',
            label: 'Export Data',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'purchase',
    label: 'Purchase',
    moduleAccess: {
      key: 'PURCHASE_MODULE_ACCESS',
      label: 'Access Purchase Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'general',
        refSlug: 'general-purchase',
        permissions: [
          {
            key: 'PURCHASE_GENERAL_PURCHASE_VIEW',
            label: 'View General Purchase',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'PURCHASE_GENERAL_PURCHASE_CREATE',
            label: 'Create General Purchase',
            action: 'create',
            kind: 'crud',
          },
          {
            key: 'PURCHASE_GENERAL_PURCHASE_UPDATE',
            label: 'Update General Purchase',
            action: 'update',
            kind: 'crud',
          },
          {
            key: 'PURCHASE_GENERAL_PURCHASE_DELETE',
            label: 'Delete General Purchase',
            action: 'delete',
            kind: 'crud',
          },
        ],
      },
    ],
  },
  {
    sectionKey: 'inventory',
    label: 'Inventory',
    moduleAccess: {
      key: 'INVENTORY_MODULE_ACCESS',
      label: 'Access Inventory Module',
      action: 'access',
      kind: 'module',
    },
    features: [
      {
        navSlug: 'stock',
        refSlug: 'stock',
        permissions: [
          {
            key: 'INVENTORY_STOCK_VIEW',
            label: 'View Stock',
            action: 'view',
            kind: 'crud',
          },
          {
            key: 'INVENTORY_STOCK_EXPORT',
            label: 'Export Stock',
            action: 'export',
            kind: 'custom',
          },
        ],
      },
    ],
  },
]

/**
 * Every menu slug this app has, in the reference's own vocabulary — its 8 module slugs plus the
 * 44 feature slugs, 52 in all.
 *
 * Emitted here rather than kept only in `reference-menu-map.cjs` so a test can compare it with
 * `data/menus.json` without importing an untyped CommonJS module.
 */
export const REFERENCE_MENU_SLUGS: string[] = [
  'administration',
  'attributes',
  'backup',
  'billing',
  'branches',
  'cashbook',
  'categories',
  'company',
  'device-purchase',
  'device-purchase-register',
  'device-sale',
  'device-sale-register',
  'device-stock',
  'expenses',
  'field-visit-report',
  'finance',
  'financial-years',
  'general-purchase',
  'inventory',
  'invoices',
  'ip-whitelist',
  'items',
  'job-cards',
  'job-costing',
  'ledger',
  'login-report',
  'masters',
  'parties',
  'party-categories',
  'payables',
  'payment-modes',
  'period-summary',
  'pnl-report',
  'print-formats',
  'profit-loss',
  'purchase',
  'receipts',
  'receivables',
  'reports',
  'roles',
  'sales',
  'second-hand-device',
  'service',
  'service-items',
  'service-options',
  'service-reports',
  'sessions',
  'settings',
  'stock',
  'supplier-payables',
  'supplier-report',
  'system-audit',
  'technician-report',
  'uom',
  'users',
  'whatsapp-settings',
  'workflow-designer',
]

/** Every permission key in the catalogue. */
export const ALL_PERMISSION_KEYS: string[] = PERMISSION_CATALOGUE.flatMap((m) => [
  m.moduleAccess.key,
  ...m.features.flatMap((f) => f.permissions.map((p) => p.key)),
])

/** The module a permission key belongs to, or undefined for a key that is not in the catalogue. */
export function moduleForPermission(key: string): PermissionModuleSpec | undefined {
  return PERMISSION_CATALOGUE.find(
    (m) =>
      m.moduleAccess.key === key || m.features.some((f) => f.permissions.some((p) => p.key === key))
  )
}

/** Every key one module contributes, for its "select all" and its count badge. */
export function keysForModule(m: PermissionModuleSpec): string[] {
  return [m.moduleAccess.key, ...m.features.flatMap((f) => f.permissions.map((p) => p.key))]
}
