import type {
  PrintDocumentType,
  PrintMargins,
  PrintPaper,
  PrintSettings,
  PrintTemplateCategory,
} from '@/types/firestore'

/**
 * The default template catalogue — 19 templates across the 11 document types, transcribed
 * verbatim from `data/document-templates.json` (paper size, margins, print settings, preset key
 * and which one is default, per document type). Generated from that file rather than typed by
 * hand, so the numbers can't drift from the source they came from.
 *
 * The source export carries no element/layout data at all (`extraSlots` is empty on all 19), so
 * the actual designed content for each of these is authored separately in
 * `print-layouts.ts` — see that file's own comment.
 */
export interface PrintPresetDef {
  documentType: PrintDocumentType
  category: PrintTemplateCategory
  presetKey: string | null
  isDefault: boolean
  name: string
  paper: PrintPaper
  margins: PrintMargins
  settings: PrintSettings
}

export const PRINT_PRESETS: PrintPresetDef[] = [
  {
    documentType: 'barcodeLabel',
    category: 'label',
    presetKey: null,
    isDefault: true,
    name: 'Default Barcode Label',
    paper: { width: 40, height: 20, unit: 'mm', orientation: 'landscape' },
    margins: { top: 1, right: 1, bottom: 1, left: 1 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'customerLabel',
    category: 'label',
    presetKey: null,
    isDefault: true,
    name: 'Default Customer Label',
    paper: { width: 50, height: 25, unit: 'mm', orientation: 'landscape' },
    margins: { top: 1, right: 1, bottom: 1, left: 1 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'deviceTagLabel',
    category: 'label',
    presetKey: null,
    isDefault: true,
    name: 'Default Device Tag Label',
    paper: { width: 50, height: 25, unit: 'mm', orientation: 'landscape' },
    margins: { top: 1, right: 1, bottom: 1, left: 1 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'jobCardBill',
    category: 'bill',
    presetKey: '58mm',
    isDefault: true,
    name: 'Default Job Card Bill (58mm)',
    paper: { width: 58, height: 190, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'jobCardBill',
    category: 'bill',
    presetKey: '80mm',
    isDefault: false,
    name: 'Default Job Card Bill (80mm)',
    paper: { width: 80, height: 190, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'jobCardBill',
    category: 'bill',
    presetKey: 'a4',
    isDefault: false,
    name: 'Default Job Card Bill (A4)',
    paper: { width: 210, height: 297, unit: 'mm', orientation: 'portrait' },
    margins: { top: 15, right: 15, bottom: 15, left: 15 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'jobCard',
    category: 'bill',
    presetKey: '58mm',
    isDefault: true,
    name: 'Default Job Card (58mm)',
    paper: { width: 58, height: 120, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'jobCard',
    category: 'bill',
    presetKey: '80mm',
    isDefault: false,
    name: 'Default Job Card (80mm)',
    paper: { width: 80, height: 120, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'paymentReceipt',
    category: 'bill',
    presetKey: '58mm',
    isDefault: true,
    name: 'Default Payment Receipt (58mm)',
    paper: { width: 58, height: 90, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'paymentReceipt',
    category: 'bill',
    presetKey: '80mm',
    isDefault: false,
    name: 'Default Payment Receipt (80mm)',
    paper: { width: 80, height: 90, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'productLabel',
    category: 'label',
    presetKey: null,
    isDefault: true,
    name: 'Default Product Label',
    paper: { width: 50, height: 25, unit: 'mm', orientation: 'landscape' },
    margins: { top: 1, right: 1, bottom: 1, left: 1 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'purchaseReceipt',
    category: 'bill',
    presetKey: '58mm',
    isDefault: true,
    name: 'Default Purchase Receipt (58mm)',
    paper: { width: 58, height: 130, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'purchaseReceipt',
    category: 'bill',
    presetKey: '80mm',
    isDefault: false,
    name: 'Default Purchase Receipt (80mm)',
    paper: { width: 80, height: 130, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'secondHandDeviceLabel',
    category: 'label',
    presetKey: null,
    isDefault: true,
    name: 'Default Second Hand Device Label',
    paper: { width: 50, height: 25, unit: 'mm', orientation: 'landscape' },
    margins: { top: 1, right: 1, bottom: 1, left: 1 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'secondHandPurchaseReceipt',
    category: 'bill',
    presetKey: '58mm',
    isDefault: true,
    name: 'Default Second Hand Device Purchase Receipt (58mm)',
    paper: { width: 58, height: 130, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'secondHandPurchaseReceipt',
    category: 'bill',
    presetKey: '80mm',
    isDefault: false,
    name: 'Default Second Hand Device Purchase Receipt (80mm)',
    paper: { width: 80, height: 130, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'secondHandSaleInvoice',
    category: 'bill',
    presetKey: '58mm',
    isDefault: true,
    name: 'Default Second Hand Device Sale Invoice (58mm)',
    paper: { width: 58, height: 130, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'secondHandSaleInvoice',
    category: 'bill',
    presetKey: '80mm',
    isDefault: false,
    name: 'Default Second Hand Device Sale Invoice (80mm)',
    paper: { width: 80, height: 130, unit: 'mm', orientation: 'portrait' },
    margins: { top: 3, right: 3, bottom: 3, left: 3 },
    settings: {
      copies: 1,
      duplicateCopy: false,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
  {
    documentType: 'secondHandSaleInvoice',
    category: 'bill',
    presetKey: 'a4-duplicate',
    isDefault: false,
    name: 'Default Second Hand Device Sale Invoice (A4, Duplicate Copy)',
    paper: { width: 210, height: 148.5, unit: 'mm', orientation: 'portrait' },
    margins: { top: 8, right: 8, bottom: 8, left: 8 },
    settings: {
      copies: 1,
      duplicateCopy: true,
      duplicateCopyDirection: 'stacked',
      ups: 1,
      gapMm: 2,
      printSpeed: 4,
      printDensity: 8,
    },
  },
]

/** Every preset for one document type, in catalogue order. */
export function presetsFor(documentType: PrintDocumentType): PrintPresetDef[] {
  return PRINT_PRESETS.filter((p) => p.documentType === documentType)
}
